package org.talend.survivorship.CITELINE 

rule "rSpeciality"
    no-loop true
    dialect "mvel"
    ruleflow-group "rSpecialityGroup"
when
    $input : RecordIn( speciality.equals('CITELINE'), dataset.isLongest( speciality, "Speciality", false) )  
then
    dataset.survive( $input.TALEND_INTERNAL_ID, "Speciality", drools.getRule().getName());
    dataset.survive( $input.TALEND_INTERNAL_ID, "Source", drools.getRule().getName());

end


